app:
  name: python-backend
  image: ortoss/python-backend
  tag: latest
  port: 5000
  replicas: 2


resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"


ingress:
  enabled: true
  host: app.studentort.devops8.test-danit.com
  className: nginx


service:
  type: ClusterIP
  port: 80
  targetPort: 5000
